### ISSUE TITLE
Make :STRING the default field type

### ISSUE THREAD

**Issue by szarnyasg** [szarnyasg/neo4j-apoc-procedures#2]

**Comment by hegyibalint** [comment]
Because of the CONVERTER defaults to `%s` (https://github.com/szarnyasg/neo4j-apoc-procedures/blob/3.2-load-csv/src/main/java/apoc/export/csv/CsvHeaderToCypherConverter.java#L217), this is not solved already?

**Comment by szarnyasg** [comment]
The problem is that the regex does not match in cases where there is no `:SOME_TYPE` in the field.
